CREATE DATABASE IF NOT EXISTS students_db;
USE students_db;
CREATE TABLE IF NOT EXISTS students (id INT AUTO_INCREMENT PRIMARY KEY, student_id VARCHAR(50) NOT NULL UNIQUE, full_name VARCHAR(120) NOT NULL, email VARCHAR(160) NOT NULL UNIQUE, course VARCHAR(120) NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
