apiVersion: v1
kind: Secret
metadata: {name: mysql-secret}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: students_db
  MYSQL_USER: student_user
  MYSQL_PASSWORD: student_password
